export const landingPageData = {
  header: {
    title: "HealthTrack",
    subtitle: "Your partner in achieving a healthier lifestyle.",
    logo: "https://img.freepik.com/free-vector/bird-colorful-gradient-design-vector_343694-2506.jpg?size=338&ext=jpg&ga=GA1.1.2008272138.1724716800&semt=ais_hybrid",
  },
 slides : [
    {
      title: 'Welcome to HealthTrack',
      description: 'Explore our premium health and wellness programs',
      img: 'https://images6.alphacoders.com/774/thumb-1920-774315.jpg',
    },
    {
      title: 'Discover Your Inner Strength',
      description: 'Personalized health care for a better you',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSi-OfeL5pEFGRIRmw4Pfasaa5UMtV5B5C6Q&s', 
    },
    {
      title: 'Achieve Your Health Goals',
      description: 'Programs and resources for every lifestyle',
      img: 'https://www.forgept.com/wp-content/smush-webp/2024/03/Forge-Blog-Graphics-1920-%C3%97-600-px-52.png.webp',
    },
  ],
  features: [
    {
      id: 1,
      icon: "🏃‍♂️",
      title: "Activity Monitoring",
      description: "Keep track of your daily steps, workouts, and physical activities.",
      button : "learn more"
    },
    {
      id: 2,
      icon: "🍎",
      title: "Nutrition Planning",
      description: "Plan your meals and track your nutritional intake to maintain a balanced diet.",
      button : "learn more"
    },
    {
      id: 3,
      icon: "🧘‍♀️",
      title: "Mental Wellness",
      description: "Practice mindfulness and track your mental well-being with guided meditations.",
      button : "learn more"
    },
  ],
  healthProducts: [
    {
      id: 1,
    title: "Organic Protein Powder",
    category: "Supplements",
    price: 29.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Boost your protein intake with our organic, plant-based protein powder."
  },
  {
    id: 2,
    title: "Multivitamin Supplement",
    category: "Supplements",
    price: 19.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Complete your daily nutrient intake with our all-in-one multivitamin."
  },
  {
    id: 3,
    title: "Yoga Mat",
    category: "Fitness Equipment",
    price: 49.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "High-quality, non-slip yoga mat for your daily practice."
  },
  {
    id: 4,
    title: "Fitness Tracker",
    category: "Gadgets",
    price: 99.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Track your steps, calories burned, and sleep patterns with our advanced fitness tracker."
  },
  {
    id: 5,
    title: "Herbal Detox Tea",
    category: "Beverages",
    price: 14.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Cleanse your body with our natural, herbal detox tea blend."
  },
  {
    id: 6,
    title: "Resistance Bands Set",
    category: "Fitness Equipment",
    price: 24.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Enhance your workouts with our durable and versatile resistance bands set."
  },
  {
    id: 7,
    title: "Essential Oil Diffuser",
    category: "Wellness",
    price: 39.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Create a calming atmosphere with our stylish and effective essential oil diffuser."
  },
  {
    id: 8,
    title: "Keto Snack Bars",
    category: "Snacks",
    price: 19.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Stay on track with your keto diet with our delicious and low-carb snack bars."
  },
  {
    id: 9,
    title: "Foam Roller",
    category: "Fitness Equipment",
    price: 29.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Relieve muscle tension and improve flexibility with our high-density foam roller."
  },
  {
    id: 10,
    title: "Vitamin D3 Supplement",
    category: "Supplements",
    price: 12.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Support your bone health and immune system with our Vitamin D3 supplement."
  },
  {
    id: 11,
    title: "Collagen Peptides",
    category: "Supplements",
    price: 34.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Support your skin, hair, nails, and joints with our collagen peptides powder.",
  },
  {
    id: 12,
    title: "Massage Gun",
    category: "Fitness Equipment",
    price: 149.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Relieve muscle soreness and enhance recovery with our portable massage gun.",
  },
  {
    id: 13,
    title: "Pre-Workout Powder",
    category: "Supplements",
    price: 29.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Boost your energy and performance with our powerful pre-workout powder.",
  },
  {
    id: 14,
    title: "Stainless Steel Water Bottle",
    category: "Accessories",
    price: 24.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Stay hydrated with our insulated, stainless steel water bottle.",
  },
  {
    id: 15,
    title: "Sleep Aid Supplement",
    category: "Wellness",
    price: 19.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Improve your sleep quality with our natural sleep aid supplement.",
  },  
  {
    id: 16,
    title: "Jump Rope",
    category: "Fitness Equipment",
    price: 14.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Get an intense cardio workout with our durable and adjustable jump rope.",
  },
  {
    id: 17,
    title: "Apple Cider Vinegar Gummies",
    category: "Supplements",
    price: 21.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Support digestion and overall health with our apple cider vinegar gummies.",
  },
  {
    id: 18,
    title: "Yoga Block",
    category: "Fitness Equipment",
    price: 9.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Enhance your yoga practice with our lightweight and supportive yoga block.",
  },
  {
    id: 19,
    title: "Vitamin C Serum",
    category: "Beauty",
    price: 29.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Brighten and hydrate your skin with our potent Vitamin C serum.",
  },
  {
    id: 20,
    title: "Hair, Skin & Nails Gummies",
    category: "Supplements",
    price: 16.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Support healthy hair, skin, and nails with our biotin-rich gummies.",
  },
  {
    id: 21,
    title: "Essential Oil Set",
    category: "Wellness",
    price: 24.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Relax and rejuvenate with our premium essential oil set for aromatherapy.",
  },
  {
    id: 22,
    title: "Post-Workout Recovery Drink",
    category: "Supplements",
    price: 34.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Recover faster with our post-workout drink packed with electrolytes and protein.",
  },
  {
    id: 23,
    title: "Hand Grip Strengthener",
    category: "Fitness Equipment",
    price: 14.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Improve your grip strength with our adjustable hand grip strengthener.",
  },
  {
    id: 24,
    title: "Organic Matcha Powder",
    category: "Beverages",
    price: 19.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Boost your energy and focus with our organic matcha green tea powder.",
  },
  {
    id: 25,
    title: "Toning Cream",
    category: "Beauty",
    price: 39.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Firm and tone your skin with our sculpting body cream.",
  },  
  {
    id: 26,
    title: "Plant-Based Protein Bars",
    category: "Snacks",
    price: 24.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Fuel your day with our delicious and nutritious plant-based protein bars.",
  },
  {
    id: 27,
    title: "Whey Protein Isolate",
    category: "Supplements",
    price: 49.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Maximize muscle recovery with our high-quality whey protein isolate.",
  },
  {
    id: 28,
    title: "Meditation Cushion",
    category: "Wellness",
    price: 59.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Find your inner peace with our comfortable and supportive meditation cushion.",
  },
  {
    id: 29,
    title: "Coconut Oil",
    category: "Beauty",
    price: 14.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Moisturize your skin and hair with our pure and natural coconut oil.",
  },
  {
    id: 30,
    title: "Portable Blender",
    category: "Gadgets",
    price: 49.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Blend your smoothies and shakes on the go with our compact portable blender.",
  },
  {
    id: 31,
    title: "Green Superfood Powder",
    category: "Supplements",
    price: 39.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Boost your daily nutrient intake with our powerful green superfood powder.",
  },
  {
    id: 32,
    title: "Infrared Sauna Blanket",
    category: "Wellness",
    price: 199.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Experience the benefits of an infrared sauna at home with our sauna blanket.",
  },
  {
    id: 33,
    title: "Meal Prep Containers",
    category: "Accessories",
    price: 24.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Organize your meals for the week with our BPA-free meal prep containers.",
  },
  {
    id: 34,
    title: "Turmeric Capsules",
    category: "Supplements",
    price: 14.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Support your joint health and reduce inflammation with our turmeric capsules.",
  },
  {
    id: 35,
    title: "Omega-3 Fish Oil",
    category: "Supplements",
    price: 19.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Support heart and brain health with our high-potency Omega-3 fish oil supplement.",
  },
  {
    id: 36,
    title: "Adjustable Dumbbells",
    category: "Fitness Equipment",
    price: 199.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Customize your strength training with our space-saving adjustable dumbbells.",
  },
  {
    id: 37,
    title: "Probiotic Capsules",
    category: "Supplements",
    price: 24.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Improve your digestion and gut health with our daily probiotic capsules.",
  },
  {
    id: 38,
    title: "Bluetooth Smart Scale",
    category: "Gadgets",
    price: 49.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Track your weight, BMI, and body fat with our Bluetooth-enabled smart scale.",
  },
  {
    id: 39,
    title: "Electric Heated Blanket",
    category: "Wellness",
    price: 59.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Stay warm and cozy with our electric heated blanket, perfect for relaxation.",
  },  
  {
    id: 40,
    title: "Acupressure Mat",
    category: "Fitness Equipment",
    price: 29.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Relieve stress and muscle tension with our acupressure mat for deep relaxation.",
  },
  {
    id: 41,
    title: "Hair Growth Serum",
    category: "Beauty",
    price: 39.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Stimulate hair growth and strengthen your hair with our nourishing serum.",
  },
  {
    id: 42,
    title: "Sleep Mask",
    category: "Accessories",
    price: 9.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Block out light and improve your sleep quality with our comfortable sleep mask.",
  },
  {
    id: 43,
    title: "Vegan Collagen Booster",
    category: "Supplements",
    price: 34.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Enhance your skin's elasticity with our plant-based collagen booster.",
  },
  {
    id: 44,
    title: "Compression Socks",
    category: "Accessories",
    price: 19.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Improve circulation and reduce fatigue with our high-quality compression socks.",
  },
  {
    id: 45,
    title: "Hydrating Face Mask",
    category: "Beauty",
    price: 14.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Replenish moisture and refresh your skin with our hydrating sheet mask.",
  },
  {
    id: 46,
    title: "Foam Massage Ball",
    category: "Fitness Equipment",
    price: 9.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Ease muscle knots and tension with our compact foam massage ball.",
  },
  {
    id: 47,
    title: "Organic Spirulina Powder",
    category: "Supplements",
    price: 29.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Boost your energy and immunity with our nutrient-rich organic spirulina powder.",
  },
  {
    id: 48,
    title: "Body Scrub",
    category: "Beauty",
    price: 19.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Exfoliate and soften your skin with our natural body scrub.",
  },
  {
    id: 49,
    title: "Silk Pillowcase",
    category: "Accessories",
    price: 24.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Reduce hair frizz and wrinkles with our luxurious silk pillowcase.",
  },
  {
    id: 50,
    title: "Herbal Sleep Tea",
    category: "Beverages",
    price: 12.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Relax and unwind with our calming herbal sleep tea blend.",
  },
  {
    id: 51,
    title: "BCAA Powder",
    category: "Supplements",
    price: 34.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Improve muscle recovery and reduce soreness with our BCAA powder.",
  },
  {
    id: 52,
    title: "Dry Brush",
    category: "Beauty",
    price: 14.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Exfoliate and improve circulation with our natural bristle dry brush.",
  },
  {
    id: 53,
    title: "Reusable Bamboo Straws",
    category: "Accessories",
    price: 9.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Reduce plastic waste with our eco-friendly reusable bamboo straws.",
  },
  {
    id: 54,
    title: "Vitamin B12 Spray",
    category: "Supplements",
    price: 24.99,
    img: "https://via.placeholder.com/300/CCCCCC",
    description: "Boost your energy levels and support brain function with our B12 spray.",
  },
    ],
  testimonials: [
    {
      id: 1,
      name: "Alice Johnson",
      quote: "HealthTrack transformed my life. I'm now more active and mindful of my health.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    {
      id: 2,
      name: "Mark Lee",
      quote: "The nutrition planning feature is amazing. I’ve achieved my weight goals effortlessly.",
      avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    },
  ],
  pricing: [
    {
      id: 1,
      plan: "Free",
      price:  0,
      features: ["Basic Activity Monitoring", "Nutrition Planning", "Community Support"],
    },
    {
      id: 2,
      plan: "Premium",
      price:  14.99,
      features: ["All Free Features", "Advanced Analytics", "Personalized Coaching"],
      status: "HOT"
    },
    {
      id: 3,
      plan: "Pro",
      price:  29.99,
      features: ["All Premium Features", "1-on-1 Virtual Consultations", "Priority Support"],
    },
    {
      id: 4,
      plan: "Ultra",
      price:  59.99,
      features: ["All Pro Features", "Dedicated Manager", "24/7 VIP Support", "Exclusive Content Access"],
    },
  ],
  callToAction: {
    title: "Start Your Journey to Better Health!",
    description: "Sign up today and take the first step towards a healthier, happier you.",
    buttonText: "Get Started",
    image: "https://images.unsplash.com/photo-1598970434795-0c54fe7c0648?w=800&auto=format&fit=crop",
  },
  footer: {
    copyright: "© 2024 HealthTrack. All rights reserved.",
  },
};

export default landingPageData;
